// First-run snapshot for the Blob store.
// 5 prospects contacted 2026-08-31 + 5 family-owned prospects added 2026-09-01.
export const seed = {
  "lastPollAt": "2026-09-01T07:00:07.411Z",
  "prospects": [
    {
      "id": "ancoats-coffee-co",
      "business": "Ancoats Coffee Co.",
      "email": "hello@ancoats-coffee.co.uk",
      "contactName": null,
      "source": "web search — ancoats-coffee.co.uk/contact",
      "tags": [
        "cafe",
        "roastery",
        "ancoats"
      ],
      "status": "awaiting_reply",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [
        {
          "type": "initial",
          "subject": "Cleaning for Ancoats Coffee",
          "messageId": "<578dbb9b-ada1-114e-a528-462014723212@fccleaningcompany.com>",
          "sentAt": "2026-08-31T14:46:00.000Z"
        }
      ],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "bounceReason": null,
      "notes": "",
      "createdAt": "2026-08-31T14:46:00.000Z",
      "updatedAt": "2026-08-31T22:16:31.456Z",
      "autoAckAt": "2026-08-31T16:48:45.000Z",
      "autoAckSnippet": "Hey,\n\nThanks for your message!\n\nJust a follow-up to let you know your email has been received and a member of\nthe team will get back to you very soon.\n\nExpect a response in within 2-3 working days.\n\nFor anything urgent, drop us a message on our Instagram or pop in and see us.\n\nThanks,\nAncoats Coffee Co \n\n--\n\nAncoats Coffee Co.\nFollow us: Website [http://ancoats-coffee.co.uk/] | Facebook \n[https://",
      "autoAckMessageId": "cak3z6foeghjbap9njpc2fqv2hmwv-9pajqtbx1ntythkx+l1tg@mail.gmail.com",
      "location": "Ancoats",
      "address": "Unit 9, Royal Mills, 17 Redhill Street, Manchester M4 5BA",
      "phone": "0161 228 3211",
      "preferredChannel": null,
      "calls": []
    },
    {
      "id": "cotton",
      "business": "Cotton Ancoats",
      "email": "hello@cottonbakery.co.uk",
      "contactName": null,
      "source": "web search",
      "tags": [
        "cafe",
        "bakery",
        "ancoats"
      ],
      "status": "awaiting_reply",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [
        {
          "type": "initial",
          "subject": "Cleaning for Cotton",
          "messageId": "<7c99fd3a-1ffb-3b45-5574-097dfb4a7faf@fccleaningcompany.com>",
          "sentAt": "2026-08-31T14:46:00.000Z"
        }
      ],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "bounceReason": null,
      "notes": "",
      "createdAt": "2026-08-31T14:46:00.000Z",
      "updatedAt": "2026-08-31T14:46:00.000Z",
      "location": "Ancoats",
      "address": "Hallé St Peter's, Blossom Street, Ancoats, Manchester M4 6BF",
      "phone": null,
      "preferredChannel": null,
      "calls": []
    },
    {
      "id": "bay-horse-tavern",
      "business": "Bay Horse Tavern",
      "email": "info@thebayhorsetavern.co.uk",
      "contactName": null,
      "source": "web search — thebayhorsetavern.co.uk",
      "tags": [
        "pub",
        "restaurant",
        "northern-quarter"
      ],
      "status": "awaiting_reply",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [
        {
          "type": "initial",
          "subject": "Cleaning for the Bay Horse Tavern",
          "messageId": "<2da93ff6-466e-2e1e-de72-d66c85ab7671@fccleaningcompany.com>",
          "sentAt": "2026-08-31T14:46:00.000Z"
        }
      ],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "bounceReason": null,
      "notes": "",
      "createdAt": "2026-08-31T14:46:00.000Z",
      "updatedAt": "2026-08-31T14:46:00.000Z",
      "location": "Northern Quarter",
      "address": "35-37 Thomas Street, Manchester M4 1NA",
      "phone": "0161 669 5799",
      "preferredChannel": null,
      "calls": []
    },
    {
      "id": "bundobust",
      "business": "Bundobust",
      "email": "hello@bundobust.com",
      "contactName": null,
      "source": "web search — bundobust.com/manchester",
      "tags": [
        "restaurant",
        "piccadilly",
        "multi-site"
      ],
      "status": "awaiting_reply",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [
        {
          "type": "initial",
          "subject": "Kitchen cleaning for Bundobust",
          "messageId": "<46422b7a-d0fa-81e9-4b7d-ab0ca5ee3140@fccleaningcompany.com>",
          "sentAt": "2026-08-31T14:46:00.000Z"
        }
      ],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "bounceReason": null,
      "notes": "",
      "createdAt": "2026-08-31T14:46:00.000Z",
      "updatedAt": "2026-08-31T22:16:31.456Z",
      "autoAckAt": "2026-08-31T16:52:04.000Z",
      "autoAckSnippet": "Thanks for contacting Bundobust... Re: Kitchen cleaning for Bundobust",
      "autoAckMessageId": "calh8o+zdki1p4oivt3jpwpyjywrmvckiujv-+8qtm+efrpqfqg@mail.gmail.com",
      "location": "Piccadilly",
      "address": "61 Piccadilly, Manchester M1 2AG",
      "phone": "0161 359 6757",
      "preferredChannel": null,
      "calls": []
    },
    {
      "id": "half-dozen-other",
      "business": "Half Dozen Other",
      "email": "hello@halfdozenother.co.uk",
      "contactName": null,
      "source": "web search",
      "tags": [
        "cafe",
        "circle-square"
      ],
      "status": "awaiting_reply",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [
        {
          "type": "initial",
          "subject": "Cleaning for Half Dozen Other",
          "messageId": "<9682c444-eef5-4124-abd1-ee05f5437a40@fccleaningcompany.com>",
          "sentAt": "2026-08-31T14:46:00.000Z"
        }
      ],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "bounceReason": null,
      "notes": "",
      "createdAt": "2026-08-31T14:46:00.000Z",
      "updatedAt": "2026-08-31T14:46:00.000Z",
      "location": "Circle Square",
      "address": "Circle Square, 1 Symphony Park, Manchester M1 7FS",
      "phone": null,
      "preferredChannel": null,
      "calls": []
    },
    {
      "id": "the-pearl",
      "business": "The Pearl",
      "email": "hello@thepearlmcr.com",
      "contactName": "Sam Taylor & Melissa Gage",
      "source": "thepearlmcr.com/contact",
      "address": "425 Bury New Road, Prestwich, Manchester M25 1AF",
      "location": "Prestwich",
      "phone": "0161 526 3667",
      "preferredChannel": null,
      "tags": [
        "restaurant",
        "british",
        "family-run"
      ],
      "status": "draft",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [],
      "calls": [],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "autoAckAt": null,
      "autoAckSnippet": null,
      "autoAckMessageId": null,
      "bounceReason": null,
      "notes": "Husband-and-wife team, community-crowdfunded. Owner-run.",
      "createdAt": "2026-09-01T00:00:00.000Z",
      "updatedAt": "2026-09-01T00:00:00.000Z"
    },
    {
      "id": "scrumptious-tea-rooms",
      "business": "Scrumptious Tea Rooms",
      "email": "c12jue@icloud.com",
      "contactName": null,
      "source": "scrumptioustearooms.com",
      "address": "8 Church Road, Urmston, Manchester M41 9BU",
      "location": "Urmston",
      "phone": "0161 425 3400",
      "preferredChannel": null,
      "tags": [
        "tearoom",
        "cafe",
        "family-run"
      ],
      "status": "draft",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [],
      "calls": [],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "autoAckAt": null,
      "autoAckSnippet": null,
      "autoAckMessageId": null,
      "bounceReason": null,
      "notes": "Family run tea room. Owner uses a personal iCloud address — deals with everything directly.",
      "createdAt": "2026-09-01T00:00:00.000Z",
      "updatedAt": "2026-09-01T00:00:00.000Z"
    },
    {
      "id": "olio-didsbury",
      "business": "OLIO Didsbury",
      "email": "info@olioflames.co.uk",
      "contactName": null,
      "source": "olioflames.co.uk",
      "address": "747 Wilmslow Road, Didsbury, Manchester M20 6RN",
      "location": "Didsbury",
      "phone": "0161 400 8112",
      "preferredChannel": null,
      "tags": [
        "restaurant",
        "mediterranean",
        "family-run"
      ],
      "status": "draft",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [],
      "calls": [],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "autoAckAt": null,
      "autoAckSnippet": null,
      "autoAckMessageId": null,
      "bounceReason": null,
      "notes": "Family-run Mediterranean / Turkish / Italian.",
      "createdAt": "2026-09-01T00:00:00.000Z",
      "updatedAt": "2026-09-01T00:00:00.000Z"
    },
    {
      "id": "eden-monton",
      "business": "Eden Monton",
      "email": "bookings@edenmonton.co.uk",
      "contactName": null,
      "source": "edenmonton.co.uk/contact",
      "address": "233-235 Monton Road, Eccles, Manchester M30 9PS",
      "location": "Monton",
      "phone": "0161 222 6412",
      "preferredChannel": null,
      "tags": [
        "restaurant",
        "italian",
        "family-run"
      ],
      "status": "draft",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [],
      "calls": [],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "autoAckAt": null,
      "autoAckSnippet": null,
      "autoAckMessageId": null,
      "bounceReason": null,
      "notes": "Award-winning family-run Italian in Monton Village.",
      "createdAt": "2026-09-01T00:00:00.000Z",
      "updatedAt": "2026-09-01T00:00:00.000Z"
    },
    {
      "id": "backs-deli",
      "business": "Back's Deli",
      "email": "shop@backsdeli.com",
      "contactName": null,
      "source": "backsdeli.com",
      "address": "62 Heaton Moor Road, Heaton Moor, Stockport SK4 4NZ",
      "location": "Heaton Moor",
      "phone": "0161 432 3309",
      "preferredChannel": null,
      "tags": [
        "deli",
        "independent",
        "family-owned"
      ],
      "status": "draft",
      "followUpIntervalDays": 5,
      "maxFollowUps": 2,
      "sends": [],
      "calls": [],
      "followUpsSent": 0,
      "lastReplyAt": null,
      "replySnippet": null,
      "replyMessageId": null,
      "autoAckAt": null,
      "autoAckSnippet": null,
      "autoAckMessageId": null,
      "bounceReason": null,
      "notes": "Independent family-owned delicatessen — deli counter, prep area, wines.",
      "createdAt": "2026-09-01T00:00:00.000Z",
      "updatedAt": "2026-09-01T00:00:00.000Z"
    }
  ]
};
